---
- hosts: lamp
  remote_user: playground
  become: yes

  tasks:
    - name: Update all packages on a Debian/Ubuntu
      apt:
        update_cache: yes
        upgrade: dist
        force_apt_get: yes

    - name: Check disk space and memory
      shell: free -m && df -h