---
- hosts: db_hosts
  remote_user: ubuntu
  become: yes
  
  tasks:
    - name: Update all packages on a Debian/Ubuntu
      apt:
        update_cache: yes
        upgrade: dist

  tasks:
    - name: Check disk space and memory
      shell: free -m && df -h

