- name: Update all packages on a Debian/Ubuntu
  apt:
    update_cache: yes
    upgrade: dist
    force_apt_get: yes
  
- name: install curl
  apt:
    name: curl
    state: present
    update_cache: yes
    force_apt_get: yes

- name: Create a webadmin group
  group:
    name: webadmin
    state: present
