- name: set mysql root password
  debconf:
    name: mysql-server
    question: mysql-server/root_password
    value: "{{ mysql_root_password }}"
    vtype: password
  tags: ['mysql']

- name: confirm mysql root password
  debconf:
    name: mysql-server
    question: mysql-server/root_password_again
    value: "{{ mysql_root_password }}"
    vtype: password
  tags: ['mysql']

- name: install mysql-python
  apt: 
    name: python-mysqldb
    state: present
  tags: ['mysql']

- name: install mysqlserver
  apt:
    name: "{{ item }}"
    state: present 
  with_items:
    - mysql-server
    - mysql-client
  tags: ['mysql']
  
- include: harden.yml