- name: install php7
  apt:
    name: "{{ item }}"
    state: present

  with_items:
    - php7.2-mysql
    - php7.2-curl
    - php7.2-json
    - php7.2-cgi
    - php7.2
    - libapache2-mod-php7.2

- name: restart apache2
  systemd:
    state: restarted
    name: apache2
    daemon_reload: yes