- name: install php7
  apt:
    name:
      ['php7.2-mysql', 'php7.2-curl', 'php7.2-json', 'php7.2-cgi', 'php7.2', 'libapache2-mod-php7.2']
    state: present
    force_apt_get: yes
  notify:
    - restart apache2
  tags: ["web"]
  