- name: Wordpresss | Create new user
  user:
    name: "{{ new_user_name }}"
    password: "{{ 'new_user_password' | password_hash('sha512') }}"  
    shell: /bin/bash
    update_password: on_create
    groups: sudo,webadmin
    append: yes


- name: Wordpresss | Ensure that installation directory exists
  file: 
    path: "{{wp_install_dir|dirname}}" 
    state: directory

- name: Wordpresss | Download {{wp_version}} to /tmp
  get_url: 
    url: "http://wordpress.org/wordpress-{{wp_version}}.tar.gz" 
    force: no 
    dest: /tmp/wordpress-{{wp_version}}.tar.gz

- name: Wordpresss | Extract archive
  unarchive: 
    src: "/tmp/wordpress-{{wp_version}}.tar.gz" 
    dest: /tmp 
    copy: no

- name: Wordpresss | Move extracted directory to {{wp_install_dir}}
  command: /bin/mv /tmp/wordpress "{{wp_install_dir}}"
  args:
    creates: "{{wp_install_dir}}"

- name: Wordpresss | Remove wordpress-{{wp_version}}.tar.gz
  file: 
    path: "/tmp/wordpress-{{wp_version}}.tar.gz" 
    state: absent

- name: Wordpresss | Configure WordPress to use MySQL and PHP
  template:
    src: wp.conf.j2
    dest: /etc/wordpress/config-localhost.php
    owner: root
    group: root
    mode: 0644

- name: Wordpress | Link the WordPress files to the desired location on your web server
  file:
    src: '{{wp_install_dir}}'
    dest: /var/www/html/wordpress
    owner: root
    group: root
    state: link
    shell: mv /etc/wordpress/config-localhost.php /etc/wordpress/config-default.php

# - name: In a working directory, create a text file wordpress.sql to configure the WordPress database.
# touch wordpress.sql
# CREATE DATABASE wordpress;
# GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.*
# TO wordpress@localhost
# IDENTIFIED BY 'yourPassword';
# FLUSH PRIVILEGES;

# - name: Create WP database
# cat wordpress.sql | sudo mysql --defaults-extra-file=/etc/mysql/debian.cnf
# After the command completes, delete the file wordpress.sql


# - name: Move the WordPress installation to the web server document root.
# sudo ln -s /usr/share/wordpress /var/www/html/wordpress
# sudo mv /etc/wordpress/config-localhost.php /etc/wordpress/config-default.php

